"""
TrustGraph AI - ORM Database Models
SQLAlchemy table definitions for transactions, alerts, and user profiles.
"""

from sqlalchemy import (
    Column, String, Float, Integer, Boolean,
    DateTime, Text, JSON
)
from sqlalchemy.sql import func
from backend.database import Base


class Transaction(Base):
    """Stores every processed transaction."""
    __tablename__ = "transactions"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    transaction_id  = Column(String(64), unique=True, index=True, nullable=False)
    user_id         = Column(String(64), index=True, nullable=False)
    amount          = Column(Float, nullable=False)
    payment_type    = Column(String(32), default="UPI")
    location        = Column(String(128), default="Unknown")
    beneficiary_id  = Column(String(64), nullable=True)
    beneficiary_type= Column(String(16), default="known")   # known | new
    device_id       = Column(String(128), nullable=True)
    trusted_device  = Column(Boolean, default=True)
    login_time      = Column(String(8), default="12:00")    # HH:MM
    is_fraud        = Column(Integer, default=0)             # 0 | 1

    # Risk analysis output
    risk_score      = Column(Integer, default=0)
    risk_level      = Column(String(16), default="LOW")
    risk_reasons    = Column(JSON, default=list)
    recommended_action = Column(String(32), default="ALLOW")
    suggested_step  = Column(String(64), nullable=True)

    created_at      = Column(DateTime(timezone=True), server_default=func.now())


class FraudAlert(Base):
    """Stores high and medium risk alerts generated by the fraud engine."""
    __tablename__ = "fraud_alerts"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    alert_id        = Column(String(64), unique=True, index=True)
    transaction_id  = Column(String(64), index=True, nullable=False)
    user_id         = Column(String(64), index=True, nullable=False)
    risk_score      = Column(Integer)
    risk_level      = Column(String(16))
    reasons         = Column(JSON, default=list)
    recommended_action = Column(String(32))
    suggested_step  = Column(String(64), nullable=True)
    status          = Column(String(32), default="OPEN")    # OPEN | REVIEWED | CLOSED
    officer_notes   = Column(Text, nullable=True)

    created_at      = Column(DateTime(timezone=True), server_default=func.now())
    updated_at      = Column(DateTime(timezone=True), onupdate=func.now())


class UserProfile(Base):
    """Stores behavioral baseline profile for each user."""
    __tablename__ = "user_profiles"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id         = Column(String(64), unique=True, index=True, nullable=False)
    usual_location  = Column(String(128), default="Unknown")
    avg_amount      = Column(Float, default=1000.0)
    max_amount      = Column(Float, default=5000.0)
    usual_login_hour= Column(Integer, default=10)           # 0–23
    known_devices   = Column(JSON, default=list)
    known_beneficiaries = Column(JSON, default=list)
    total_txns      = Column(Integer, default=0)
    fraud_txns      = Column(Integer, default=0)

    created_at      = Column(DateTime(timezone=True), server_default=func.now())
    updated_at      = Column(DateTime(timezone=True), onupdate=func.now())
