"""
TrustGraph AI - ORM Database Models
SQLAlchemy table definitions for transactions, cyber events, alerts, and user profiles.
"""

from sqlalchemy import (
    Column, String, Float, Integer, Boolean,
    DateTime, Text, JSON
)
from sqlalchemy.sql import func
from backend.database import Base


class Transaction(Base):
    """Stores every processed transaction (Legacy pipeline preserved for demo)."""
    __tablename__ = "transactions"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    transaction_id  = Column(String(64), unique=True, index=True, nullable=False)
    user_id         = Column(String(64), index=True, nullable=False)
    amount          = Column(Float, nullable=False)
    payment_type    = Column(String(32), default="UPI")
    location        = Column(String(128), default="Unknown")
    beneficiary_id  = Column(String(64), nullable=True)
    beneficiary_type= Column(String(16), default="known")   # known | new
    device_id       = Column(String(128), nullable=True)
    trusted_device  = Column(Boolean, default=True)
    login_time      = Column(String(8), default="12:00")    # HH:MM
    is_fraud        = Column(Integer, default=0)             # 0 | 1

    # Risk analysis output
    risk_score      = Column(Integer, default=0)
    risk_level      = Column(String(16), default="LOW")
    risk_reasons    = Column(JSON, default=list)
    recommended_action = Column(String(32), default="ALLOW")
    suggested_step  = Column(String(64), nullable=True)

    created_at      = Column(DateTime(timezone=True), server_default=func.now())


class CyberEvent(Base):
    """Stores every processed cyber event (login, transfer, sim swap, etc.)."""
    __tablename__ = "cyber_events"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    event_id        = Column(String(64), unique=True, index=True, nullable=False)
    user_id         = Column(String(64), index=True, nullable=False)
    event_type      = Column(String(32), nullable=False, index=True) # LOGIN, FAILED_LOGIN, TRANSFER, SIM_SWAP, etc.
    
    timestamp       = Column(DateTime(timezone=True), server_default=func.now())
    
    device_id       = Column(String(128), nullable=True)
    ip_address      = Column(String(64), nullable=True)
    location        = Column(String(128), default="Unknown")
    
    session_id      = Column(String(64), index=True, nullable=True)
    correlation_id  = Column(String(64), index=True, nullable=True)
    source          = Column(String(32), default="API") # MOBILE_APP, WEB, ATM, API
    
    severity        = Column(String(16), default="LOW") # LOW, MEDIUM, HIGH, CRITICAL
    status          = Column(String(32), default="PROCESSED") # PROCESSED, FLAGGED, BLOCKED
    
    # Flexible JSON field for event-specific data (e.g. amount, beneficiary for transactions)
    metadata_payload= Column(JSON, default=dict)
    
    # Telemetry data
    raw_telemetry   = Column(JSON, default=dict)
    telemetry_profile= Column(JSON, default=dict)
    
    # Risk analysis output
    risk_score      = Column(Integer, default=0)
    risk_level      = Column(String(16), default="LOW")


class FraudAlert(Base):
    """Stores high and medium risk alerts generated by the fraud engine."""
    __tablename__ = "fraud_alerts"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    alert_id        = Column(String(64), unique=True, index=True)
    transaction_id  = Column(String(64), index=True, nullable=True)  # Legacy
    event_id        = Column(String(64), index=True, nullable=True)  # New CyberEvent mapping
    user_id         = Column(String(64), index=True, nullable=False)
    risk_score      = Column(Integer)
    risk_level      = Column(String(16))
    reasons         = Column(JSON, default=list)
    recommended_action = Column(String(32))
    suggested_step  = Column(String(128), nullable=True)
    status          = Column(String(32), default="OPEN")    # OPEN | REVIEWED | CLOSED
    officer_notes   = Column(Text, nullable=True)

    created_at      = Column(DateTime(timezone=True), server_default=func.now())
    updated_at      = Column(DateTime(timezone=True), onupdate=func.now())


class UserProfile(Base):
    """Stores behavioral baseline profile for each user."""
    __tablename__ = "user_profiles"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id         = Column(String(64), unique=True, index=True, nullable=False)
    
    # Identity & Location
    usual_location  = Column(String(128), default="Unknown")
    trusted_locations = Column(JSON, default=list)
    known_devices   = Column(JSON, default=list)
    trusted_browsers= Column(JSON, default=list)
    
    # Behavior & Transactions
    avg_amount      = Column(Float, default=0.0)
    median_amount   = Column(Float, default=0.0)
    max_amount      = Column(Float, default=0.0)
    weekly_spending = Column(Float, default=0.0)
    daily_txn_count = Column(Integer, default=0)
    
    # Authentication
    usual_login_hour= Column(Integer, default=10)           # 0–23
    failed_login_ratio = Column(Float, default=0.0)
    
    # Relationships
    known_beneficiaries = Column(JSON, default=list)
    
    total_txns      = Column(Integer, default=0)
    fraud_txns      = Column(Integer, default=0)

    created_at      = Column(DateTime(timezone=True), server_default=func.now())
    updated_at      = Column(DateTime(timezone=True), onupdate=func.now())
