"""
TrustGraph AI – database/models.py
SQLAlchemy ORM table definitions for the fraud detection data pipeline.

Tables:
    transactions          – every processed banking transaction
    user_profiles         – behavioural baseline per user
    blacklisted_accounts  – flagged account IDs and reasons
    fraud_patterns        – known fraud patterns with risk scores
    fraud_logs            – alerts generated by the fraud engine
"""

from sqlalchemy import (
    Column, String, Float, Integer, Text, DateTime, JSON
)
from sqlalchemy.sql import func

from backend.database.db import Base


# ──────────────────────────────────────────────
# transactions
# ──────────────────────────────────────────────
class Transaction(Base):
    """Every banking transaction submitted to the detection engine."""
    __tablename__ = "transactions"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    transaction_id   = Column(String(64),  unique=True, index=True, nullable=False)
    user_id          = Column(String(64),  index=True,  nullable=False)
    amount           = Column(Float,                    nullable=False)
    location         = Column(String(128), default="Unknown")
    device           = Column(String(128), nullable=True)
    login_time       = Column(String(8),   default="12:00")   # HH:MM
    beneficiary_type = Column(String(16),  default="known")   # known | new
    payment_type     = Column(String(32),  default="UPI")

    created_at       = Column(DateTime(timezone=True), server_default=func.now())

    def to_dict(self) -> dict:
        return {
            "id":               self.id,
            "transaction_id":   self.transaction_id,
            "user_id":          self.user_id,
            "amount":           self.amount,
            "location":         self.location,
            "device":           self.device,
            "login_time":       self.login_time,
            "beneficiary_type": self.beneficiary_type,
            "payment_type":     self.payment_type,
            "created_at":       str(self.created_at),
        }


# ──────────────────────────────────────────────
# user_profiles
# ──────────────────────────────────────────────
class UserProfile(Base):
    """Behavioural baseline profile per user."""
    __tablename__ = "user_profiles"

    user_id         = Column(String(64), primary_key=True, index=True, nullable=False)
    avg_transaction = Column(Float,      default=1000.0)
    usual_location  = Column(String(128), default="Unknown")
    trusted_devices = Column(Text,        nullable=True)   # comma-separated list

    updated_at      = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    def to_dict(self) -> dict:
        return {
            "user_id":         self.user_id,
            "avg_transaction": self.avg_transaction,
            "usual_location":  self.usual_location,
            "trusted_devices": self.trusted_devices,
        }


# ──────────────────────────────────────────────
# blacklisted_accounts
# ──────────────────────────────────────────────
class BlacklistedAccount(Base):
    """Accounts flagged as fraudulent or high-risk."""
    __tablename__ = "blacklisted_accounts"

    account_id  = Column(String(64), primary_key=True, index=True, nullable=False)
    reason      = Column(Text, nullable=False)

    created_at  = Column(DateTime(timezone=True), server_default=func.now())

    def to_dict(self) -> dict:
        return {
            "account_id": self.account_id,
            "reason":     self.reason,
        }


# ──────────────────────────────────────────────
# fraud_patterns
# ──────────────────────────────────────────────
class FraudPattern(Base):
    """Known fraud signatures with associated risk scores."""
    __tablename__ = "fraud_patterns"

    pattern_id  = Column(String(32), primary_key=True, index=True, nullable=False)
    description = Column(Text,    nullable=False)
    risk_score  = Column(Integer, nullable=False)

    def to_dict(self) -> dict:
        return {
            "pattern_id":  self.pattern_id,
            "description": self.description,
            "risk_score":  self.risk_score,
        }


# ──────────────────────────────────────────────
# fraud_logs
# ──────────────────────────────────────────────
class FraudLog(Base):
    """Fraud alerts generated by the detection engine."""
    __tablename__ = "fraud_logs"

    id             = Column(Integer, primary_key=True, autoincrement=True)
    transaction_id = Column(String(64), index=True, nullable=False)
    risk_score     = Column(Integer,    nullable=False)
    risk_level     = Column(String(16), nullable=False)   # LOW | MEDIUM | HIGH | CRITICAL
    reasons        = Column(JSON,       default=list)
    timestamp      = Column(DateTime(timezone=True), server_default=func.now())

    def to_dict(self) -> dict:
        return {
            "id":             self.id,
            "transaction_id": self.transaction_id,
            "risk_score":     self.risk_score,
            "risk_level":     self.risk_level,
            "reasons":        self.reasons,
            "timestamp":      str(self.timestamp),
        }
